### PR TITLE
[WIP] Handle errors for multiple callers

### PR DESCRIPTION
**Pull request by thejchap**
- Add `ResponseException` base class with several relevant child error classes
- Catch this in router and format response with helpful info

```python
from lambda_router_python.errors import ImATeapot

@router.graphql('Query.brewCoffee')
@router.rest('POST /coffees')
@router.direct('brew_coffee')
def brew_coffee(_args: Dict):
  raise ImATeapot('need more coffee grounds')
```

Response - REST (results in 418 status code)
```json
{
  "error": {
    "name": "ImATeapot",
    "statusCode": 418,
    "message": "need more coffee grounds"
  }
}
```

Response - GraphQL/Direct Invoke
```json
{
  "errors": [{
    "name": "ImATeapot",
    "statusCode": 418,
    "message": "need more coffee grounds"
  }]
}
```

Screen Shot 2020-02-20 at 1 03 08 PM

### CODE REVIEW

**Comment by mmindenhall** [comment]
I recently [documented the authentication errors](https://guild-education.atlassian.net/wiki/spaces/PROD/pages/460030484/Backend+authentication+errors) that could be emitted by our backend GraphQL services.  We should probably adhere to that for consistency.

**Comment by thejchap** [comment]
@mmindenhall cool, seems like those would all map somehow to `Unauthorized` or `BadRequest`? so could be used like:

```python
raise BadRequest('invalid-token')
raise Unauthorized('jwt-expired')
```

etc?

I do think we need to map them all to valid HTTP response status codes so that API Gateway can return the correct status

**Comment by mmindenhall** [comment]
There are two aspects where I think we should try to conform:

1. The messages currently returned by GraphQL.  From the confluence page I linked, we'd only need to worry about the `Unauthorized` case, as the rest (expired token, malformed token, etc.) would be handled by AppSync without every invoking our lambda.
1. The shape of the error responses.

I.e., perhaps this:

```json
{
  "errors": [
    {
      "message": "need more coffee grounds",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "makeCoffee"
      ],
      "extensions": {
        "code": "ImATeapot",
        "statusCode": 418
      }
    }
  ],
  "data": null
}
```

instead of this:

```json
{
  "errors": [{
    "name": "ImATeapot",
    "statusCode": 418,
    "message": "need more coffee grounds"
  }]
}
```

**Comment by thejchap** [comment]
@mmindenhall @edbarnesG sounds good

so to re-cap:
- REST stays the same
- GraphQL re-throws the exception and lets AppSync deal with formatting
- direct gets formatted like the above

**Pull request merged**
